<form action="">
            
            <label>Data de nascimento:</label>
            <input type="date" required><br>
            <label>Primeiro e ultimo nome:</label>
            <input type="name" required><br>
            <label>Numero do documento do BI:</label>
            <input type="text" required><br>
            <label>Provincias:</label>
        <select required>
            <option>Luanda</option>
            <option>Malanje</option>
            <option>Bengo</option>
            <option>Benguela</option>
            <option>Cabinda</option>
            <option>Cunene</option>
            <option>Cuando Cubango</option>
            <option>Muxico</option>
            <option>Huila</option>
            <option>Zaire</option>
            <option>Kuanza Sul</option>
            <option>Kuanza Norte</option>
            <option>Namibe</option>
            <option>Huambo</option>
            <option>Lunda Norte</option>
            <option>Lunda Sul</option>
            <option>Uige</option>
            <option>Bie</option>
        </select><br>
            <label>Foto do cliente:</label>
            <input type="file" required><br>
            <label>Documento do BI frontal e verco:</label>
            <input type="file" required><br>
            <label>Genero:</label><br>
            <input type="radio" id="m" name="m"><br>
            <label>Masculino</label><br>
            <input type="radio" id="f" name="f"><br>
            <label>Feminino</label><br>
        
            <input type="submit" value="Avancar">
    </form>

